version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mydb
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynetwork 

  app:
    build:
      context: node
    container_name: mynode
    hostname: node
    entrypoint: wait-for db:3306 -t 60 -- docker-entrypoint.sh node index.js
    tty: true  
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules  
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: mynginx
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - mynetwork                

networks:
  mynetwork:
    driver: bridge